workspace: /tmp2/maitanha/vgu/cll_vlm

output:
  binary: "/tmp2/maitanha/vgu/cll_vlm/cll_vlm/ol_cll_logs/binary"
  label_description: "/tmp2/maitanha/vgu/cll_vlm/cll_vlm/ol_cll_logs/label_description"
  multi_label: "/tmp2/maitanha/vgu/cll_vlm/cll_vlm/ol_cll_logs/multi_label"

# Path to label description JSON (used when prompt_type=label_description, e.g. cifar100)
label_description_json: "/tmp2/maitanha/vgu/cll_vlm/cll_vlm/ol_cll_logs/qwen_cifar100_label_description.json"

data:
  dataset: "cifar100"
  mode: "train"

  paths:
    cifar10: "/tmp2/maitanha/vgu/cll_vlm/cll_vlm/data/cifar10"
    cifar20: "/tmp2/maitanha/vgu/cll_vlm/cll_vlm/data/cifar20"
    cifar100: "/tmp2/maitanha/vgu/cll_vlm/cll_vlm/data/cifar100"
    tiny200: "/tmp2/maitanha/vgu/cll_vlm/cll_vlm/data/tiny200/tiny-imagenet-200"

  shuffle_seed: 42
  num_workers: 4

models:
  llava:
    model_url: "llava-hf/llava-v1.6-mistral-7b-hf"

  llava_13b:
    model_url: "llava-hf/llava-v1.6-vicuna-13b-hf"

  qwen:
    model_url: "Qwen/Qwen2.5-VL-7B-Instruct"
  qwen3_2b: 
    model_url: "Qwen/Qwen3-VL-2B-Instruct"
  qwen3_8b:
    model_url: "Qwen/Qwen3-VL-8B-Instruct"
  qwen3_30b_a3b:
    model_url: "Qwen/Qwen3-VL-30B-A3B-Instruct"
